### ISSUE TITLE
Can you add instructions to open in unity?

### ISSUE THREAD

**Issue by iconnor** [hictooth/WildSkies#6]
Hi,

I have some kids that want to try it. We mostly have OSX but I can develop in unity. If there are any build instructions or the unity project, I am willing to have a stab at making it run. Thanks!

**Comment by hictooth** [comment]
I'm afraid I don't have the Unity project - I'm not the original developer or anything, just a fan that enjoyed the game and downloaded the compiled/bundled game assets, and packaged them to run as a standalone app. I did try decompiling it (which helped me understand how saving/loading worked), but unsurprisingly it didn't fully decompile, and combined with the fact that I don't know Unity, I didn't make an attempt at fixing the macOS bug. Sorry I can't be more helpful...

**Comment by iconnor** [comment]
Yes, you would need the unity project to do more. Was the original author the company that is not supporting it anymore? I read that the game was developed by a company that no longer has the rights to make Dragon Rider games, so it stopped working.

**Comment by hictooth** [comment]
Yep, the game was made by Aquiris Game Studio for Cartoon Network to go along with their Riders/Defenders of Berk TV show in 2012. But DreamWorks' contract with Cartoon Network presumably expired and the rest of the series went to Netflix, and the game was left with no updates on the website, until it was taken down at some point a few years ago. I think it's a safe bet that they won't even consider releasing the project since the mess of copyright would take a while to untangle, sadly.
